apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-driver-image-populator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-driver-image-populator
subjects:
  - kind: ServiceAccount
    name: csi-driver-image-populator
    namespace: kube-system
